config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :routine_poses
  resources :routines
  resources :yoga_poses, only: [:index, :show, :new, :create, :edit, :update]
  resources :body_areas, only: [:index, :show]
  post "/yoga_poses/:id/likes", to: "yoga_poses#incrementLikes"
  #custom route, http verb, url and action in controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/routine.rb
class Routine < ApplicationRecord
	belongs_to :user
	has_many :routine_poses
  has_many :yoga_poses, through: :routine_poses, dependent: :destroy
	validates :name, uniqueness:true, presence: true, length: { maximum: 50 }
	validates_format_of :name, :with => /\A[a-zA-Z0-9\s]+\z/i
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authentication, only: [:index, :new, :show, :create]
	def index
		if current_user
      @routines = current_user.routines
    else
    @routines = []
    end
	end

	def show
    @routine = find_routine
    if current_user.routines.include?(@routine)
      @routine = find_routine
    else
      redirect_to routines_path
    end
    end


	def new
  @routine = Routine.new
  end

  def create
  	@routine = current_user.routines.create(params_routine)
    if @routine.save

  	  redirect_to @routine

    else
      flash[:errors] = @routine.errors.full_messages
      render :new
    end

  end

  def edit
    find_routine
    if current_user.routines.include?(@routine)
      @routine = find_routine
    else
      render 'edit'
    end
  end

  def update
  	find_routine
  	@routine = current_user.routines
    if @routine.update(params_routine)

    redirect_to @routine[0]

    else
      flash[:errors] = @routine.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_routine
    @routine.destroy
    redirect_to routines_path
  end



  private

  def find_routine
    @routine = Routine.find(params[:id])
  end

  def params_routine
    params.require(:routine).permit(:name, :user_id)
   end

end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/edit.html.erb
<%= form_for @routine do |f| %>
<%= f.text_field :name, placeholder: 'Update your yoga routine name!', class: 'form-control' %>
<% end %>

app/views/routines/index.html.erb
<h2> My routines</h2>
<ul>
<%  @routines.each do |routine| %>
 <li>
 	<%= link_to routine.name, routine_path(routine) %>

 </li>
<% end %>
</br>
</br>
  <%=link_to "create new routine", new_routine_path %>
</br>

</ul>

app/views/routines/new.html.erb
<%= form_for @routine do |f| %>
<%= f.text_field :name, placeholder: 'Add a name for your yoga routine!', class: 'form-control' %>
<% end %>

app/views/routines/show.html.erb
<h3><%=@routine.name %></h3>
<ul>
<% @routine.routine_poses.each do |routine_pose| %>
<li>
	<%= link_to routine_pose.yoga_pose.name, routine_pose.yoga_pose %>
	<%= link_to "🗑", routine_pose_url(routine_pose)%>
</li>


<% end %>
</ul>

<%= link_to "Add poses to routine", new_routine_pose_url(@routine) %>
</br>
</br>
</br>
<%= link_to "See all my routines", routines_path %>
</br>
</br>
<%= link_to "Change routine name", edit_routine_path(@routine) %>
</br>

<%= button_to "delete #{@routine.name} routine", routine_path(@routine), method: :delete %>