config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :routine_poses
  resources :routines
  resources :yoga_poses, only: [:index, :show, :new, :create, :edit, :update]
  resources :body_areas, only: [:index, :show]
  post "/yoga_poses/:id/likes", to: "yoga_poses#incrementLikes"
  #custom route, http verb, url and action in controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_area.rb
class BodyArea < ApplicationRecord
	has_many :yoga_poses
	validates :name, uniqueness:true, presence: true
end

app/models/practitioner.rb
class Practitioner < ApplicationRecord
	has_many :routines
	before_save { self.email = email.downcase }
	validates :user_name, presence: true, uniqueness:true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password

end

app/models/routine.rb
class Routine < ApplicationRecord
	belongs_to :user
	has_many :routine_poses
  has_many :yoga_poses, through: :routine_poses, dependent: :destroy
	validates :name, uniqueness:true, presence: true, length: { maximum: 50 }
	validates_format_of :name, :with => /\A[a-zA-Z0-9\s]+\z/i
end

app/models/routine_pose.rb
class RoutinePose < ApplicationRecord
  belongs_to :routine
  belongs_to :yoga_pose
end

app/models/user.rb
class User < ApplicationRecord
	has_many :routines
	before_save { self.email = email.downcase }
	validates :user_name, presence: true, uniqueness:true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 3 }, allow_nil: true


end

app/models/yoga_pose.rb
class YogaPose < ApplicationRecord
  belongs_to :body_area
  has_many :routine_poses
  has_many :routines , through: :routine_poses
  validates :name, uniqueness:true, presence: true, length: { maximum: 255 }
  #validates_format_of :name, :with => /\A[a-zA-Z0-9\s]+\z/i
  validates :difficulty_level, numericality: {only_integer: true}
  validates_inclusion_of :difficulty_level, :in =>1..3

   def self.search(search)
   	 if search
   	 	 body_area = BodyArea.find_by(name: search)
       if body_area
       	 self.where(body_area_id: body_area)
       else
         YogaPose.all
       end
      else
        YogaPose.all
      end
   end

   def add_likes
  self.increment(:likes)
  self.save
 end

 def self.popular_poses
    YogaPose.all.order('likes desc').limit(5).to_a
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user
  private
  def authentication
     if !logged_in?
        redirect_to root_path
      end
  end


  def logged_in?
    #session[:user_id]
    !!current_user
  end


  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/body_areas_controller.rb
class BodyAreasController < ApplicationController
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authentication, only: [:index, :new, :show, :create]
	def index
		if current_user
      @routines = current_user.routines
    else
    @routines = []
    end
	end

	def show
    @routine = find_routine
    if current_user.routines.include?(@routine)
      @routine = find_routine
    else
      redirect_to routines_path
    end
    end


	def new
  @routine = Routine.new
  end

  def create
  	@routine = current_user.routines.create(params_routine)
    if @routine.save

  	  redirect_to @routine

    else
      flash[:errors] = @routine.errors.full_messages
      render :new
    end

  end

  def edit
    find_routine
    if current_user.routines.include?(@routine)
      @routine = find_routine
    else
      render 'edit'
    end
  end

  def update
  	find_routine
  	@routine = current_user.routines
    if @routine.update(params_routine)

    redirect_to @routine[0]

    else
      flash[:errors] = @routine.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_routine
    @routine.destroy
    redirect_to routines_path
  end



  private

  def find_routine
    @routine = Routine.find(params[:id])
  end

  def params_routine
    params.require(:routine).permit(:name, :user_id)
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  ##before_action :authentication required
  def new
  end

  def create
   user = User.find_by(user_name: params[:user_name])

     if user && user.authenticate(params[:password])
     session[:user_id] = user.id
     #this is how we login
      redirect_to user_path(user)
     #redirect_to routines_url
    else
       redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ##before_action :authentication required
  def new
  	@user = User.new
  end

  def show
    @user = current_user
  end


  def create
  	@user = User.new

    @user.user_name = params[:user][:user_name]
  	@user.email = params[:user][:email]
    @user.password = params[:user][:password]
     #can't use strong params becuase it excludes password so assign one by one
    if @user.save
      session[:user_id] = @user.id
      #grab user id and set it to session[:user_id] has to login

      redirect_to @user

    else
      flash[:errors] = @user.errors.full_messages

      redirect_to new_user_path
    end
  end

   def edit
    @user = current_user
     #@user = User.find(user_name: params[:id])
   end

   def update
    @user = current_user
     if @user.update(user_params)
      # Handle a successful update.
        redirect_to @user
     else
      render 'edit'
     end
  end


  private

    def user_params
      params.require(:user).permit(:user_name, :email)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  	#if !current_user
  	#   redirect_to root_path
   #  else
  	#   redirect_to root_path
   #  end
  end

end

app/controllers/yoga_poses_controller.rb
class YogaPosesController < ApplicationController

  def index
     #@yoga_poses = YogaPose.search(params[:search])
    @bodies = BodyArea.all
    if params[:body_area]
      @body = BodyArea.find(params[:body_area][:id])
      @yoga_poses = @body.yoga_poses
    else
      @yoga_poses = YogaPose.all
      @body = BodyArea.first
    end
    @yogaTop = YogaPose.popular_poses
  end

  def show
    find_pose
  end

  def new
  	 @yoga_pose = YogaPose.new
     @body_areas = BodyArea.all
  end

  def create
  	@yoga_pose =YogaPose.create(yoga_pose_params)
     if@yoga_pose.save

  	   redirect_to @yoga_pose
  	 else
  	    flash[:errors] = @yoga_pose.errors.full_messages
  	    render :new
  	 end
  end

  def edit
    @body_areas = BodyArea.all
  	find_pose
  end

  def update
  	find_pose
    if @yoga_pose.update(yoga_pose_params)

       redirect_to @yoga_pose
    else
       flash[:errors] = @yoga_pose.errors.full_messages
  	   render :edit
  	end
  end

  def incrementLikes
    @yoga_pose = YogaPose.find(params[:id])
    @yoga_pose.add_likes
    redirect_to @yoga_pose
 end

# def index
#   if params[:body_area]
#     @yoga_pose = YogaPose.where('body_area LIKE ?', "%#{params[:body_area]}%")
#   else
#     @yoga_pose = YogaPose.all
#   end
# end

  private

  def find_pose
    @yoga_pose = YogaPose.find(params[:id])
  end





  def yoga_pose_params
     params.require(:yoga_pose).permit(:name, :description, :img_url, :body_area_id, :difficulty_level, :likes, :search)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_areas_helper.rb
module BodyAreasHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/routine_poses_helper.rb
module RoutinePosesHelper
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/yoga_poses_helper.rb
module YogaPosesHelper
end

app/views/practitioners/new.html.erb
<h1>Register</h1>
<%= form_for(@practitioner) do |f| %>

<%=f.text_field :user_name, placeholder: 'Choose a user_name', class: 'form_control'%>
<%=f.text_field :email, placeholder: 'Enter your email', class: 'form_control'%>

<%=f.text_field :password, placeholder: 'Pick a password', class: 'form_control'%>

<%=f.submit%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= form_for(@user) do |f| %>

<%=f.text_field :user_name, placeholder: 'Edit your username', class: 'form_control'%>
<%=f.text_field :email, placeholder: 'Edit your email', class: 'form_control'%>

<%=f.submit%>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for(@user) do |f| %>

<%=f.text_field :user_name, placeholder: 'Choose a username', class: 'form_control'%>
<%=f.text_field :email, placeholder: 'Enter your email', class: 'form_control'%>

<%=f.text_field :password, placeholder: 'Pick a password', class: 'form_control'%>

<%=f.submit%>
<% end %>

app/views/users/show.html.erb
<h3> Hi, <%=  @user.user_name%>. Welcome to Yogi!</h3>

<h3> View all your <%= link_to "Routines", routines_url %> </h3>

<h5> <%= link_to "logout", "/sessions/:id", method: :delete %> </h5>
</br>
</br>
<p> Profile details are below: </p>
<p> Username: <%= @user.user_name %> </p>
<p> Email: <%= @user.email %> </p>
<p> <%=link_to "edit your profile", edit_user_path(current_user) %></p>

app/views/welcome/index.html.erb
<h1>Welcome to Yogi!</h1>

<p><%=link_to "log-in for returning users", new_session_url %></p>
<p><%=link_to " or register a new account", new_user_url %></p>

app/views/yoga_poses/._form.html.erb
<%= form_for @yoga_pose do |f| %>
<%= f.text_field :name, placeholder: 'Add a name for your yoga pose!', class: 'form-control' %>
<%= f.text_field :description, placeholder: 'Add a description for your yoga pose!', class: 'form-control' %>
<%= f.text_field :image_url, placeholder: 'Add an URL for your yoga pose!', class: 'form-control' %>
<%= f.text_field :difficulty_level, placeholder: 'Add a diffulty level from 1 to 3 for your yoga pose!', class: 'form-control' %>
<%= f.collection_select :body_area_id, @body_areas, :id, :name %>
<% end %>

app/views/yoga_poses/_form.erb
<%= form_for @yoga_pose do |f| %>
<%= f.text_field :name, placeholder: 'Add a name for your yoga pose!', class: 'form-control' %>
<%= f.text_field :description, placeholder: 'Add a description for your yoga pose!', class: 'form-control' %>
<%= f.text_field :img_url, placeholder: 'Add an URL for your yoga pose!', class: 'form-control' %>
<%= f.text_field :difficulty_level, placeholder: 'Add a diffulty level from 1 to 3 for your yoga pose!', class: 'form-control' %>
<%= f.collection_select :body_area_id, @body_areas, :id, :name %>
<%= f.submit %>
<% end %>

app/views/yoga_poses/edit.html.erb
<h3> Edit a pose in the database </h3>
<%= render "form" %>

app/views/yoga_poses/index.html.erb
<h2>Yoga Poses</h2>

<h3> Most liked poses</h3>

<ul>
<% @yogaTop.each do |top| %>
<li>
 	<%= link_to top.name, yoga_pose_path(top) %>
 </li>
 <% end %>
</ul>

</br>
<%= link_to "Add your favorite yoga pose to the database", new_yoga_pose_url(@yoga_pose) %>
</br>
</br>
<h5> Search Yoga Poses by Body Area</h5>
<%= form_tag(yoga_poses_path, method: :get) do %>`
<%= collection_select :body_area, :id, @bodies, :id, :name, selected: @body.id %>
<%#= text_field_tag(:search, params[:search]) %>
<%# //another idea is to use select vs collection_select
can use collection_select vs f.collection_select with simple form select("search", "id", @bodies.all.map(&:name)) %>
<%= submit_tag("Search Options") %>
<% end %>



</br>
</br>


<h4> List of all Yoga Poses</h4>
<ul>
<% @yoga_poses.each do |pose| %>
<li>
<%= link_to pose.name, yoga_pose_path(pose) %>
</li>
<% end %>

</ul>

app/views/yoga_poses/new.html.erb
<h3> Add a pose to the database </h3>
<%= render "form" %>

app/views/yoga_poses/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card purple lighten-3">  <!-- create the card -->
      <div class="card-image">              <!-- card image -->
           <img src=<%= @yoga_pose.img_url %>> <!-- img -->
<div class="card-content">            <!-- card text -->
  <h3><%= @yoga_pose.name %></h3>
        <p>Brief description: <%= @yoga_pose.description %></p>
         </br>
        <p>Level of difficulty: <%=@yoga_pose.difficulty_level %></p>
      </br>
        <p>Number of Likes: <%=@yoga_pose.likes %></p>
        <p> <%= button_to "like a yoga pose", "/yoga_poses/#{@yoga_pose.id}/likes" %> </p>
      </br>
        <p> <%= link_to "Edit Yoga Pose information", edit_yoga_pose_path(@yoga_pose) %></p>


    </div>
  </div>
  <div class="col s12">

  	</div>
</div>