config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :routine_poses
  resources :routines
  resources :yoga_poses, only: [:index, :show, :new, :create, :edit, :update]
  resources :body_areas, only: [:index, :show]
  post "/yoga_poses/:id/likes", to: "yoga_poses#incrementLikes"
  #custom route, http verb, url and action in controller
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/routine_poses_controller.rb
class RoutinePosesController < ApplicationController
  def show
    find_routine_pose
  end

  def new
  	@routine_pose = RoutinePose.new
  	@routines = current_user.routines
  	@yoga_poses = YogaPose.all
  end

  def create
  	@routine_pose = RoutinePose.new(routine_pose_params)
    @routine_pose.save
      redirect_to(@routine_pose.routine)
    	#redirect_to(@routine_pose.yoga_pose)
    	#redirect to yoga_pose show page
      #could have done @routine_pose = RoutinePose.create(routine_pose_params)
   end

  def edit
    find_routine_pose
    @routines = current_user.routines
    @yoga_poses = YogaPose.all
      render :edit
  end

  def update
    find_routine_pose
    @routine_pose.update(routine_pose_params)
  end

  def destroy
    find_routine_pose
    @routine_pose.destroy
    redirect_to routine_url(@routine_pose.routine)
    #we only have access here to @routine_pose
    #can go back to routine page and ask for @routine_pose.routine
    #it will still have @routine_pose until we hit end
    #in the method
    #we are retrieving from it the routine object so we will
    #end up at routine show page
  end



  private
    def find_routine_pose
    @routine_pose = RoutinePose.find(params[:id])
  end

  def routine_pose_params
    params.require(:routine_pose).permit(:yoga_pose_id, :routine_id)
  end


end

app/helpers/routine_poses_helper.rb
module RoutinePosesHelper
end

app/views/routine_poses/edit.html.erb
<%= form_for @routine_pose do |f| %>

<%=f.label :yoga_pose%>
<%=f.collection_select :yoga_pose_id, @yoga_poses, :id, :name %>

<%=f.label :routine%>
<%=f.collection_select :routine_id, @routines, :id, :name %>
<%= f.submit %>
<% end %>

app/views/routine_poses/new.html.erb
<h4>Choose a Pose to Add and Select the Routine Where it Belongs: </h4>
<%= form_for @routine_pose do |f| %>

<%=f.label :yoga_pose%>
<%=f.collection_select :yoga_pose_id, @yoga_poses, :id, :name %>

<%=f.label :routine%>
<%=f.collection_select :routine_id, @routines, :id, :name %>

<%= f.submit %>
<% end %>

</br>
<%= link_to "For more information on poses, you can search by body area focus", yoga_poses_url %>

app/views/routine_poses/show.html.erb
<h3><%=link_to @routine_pose.yoga_pose.name, @routine_pose %></h3>

<%= button_to "remove #{@routine_pose.yoga_pose.name} from your #{@routine_pose.routine.name} routine", routine_pose_path, method: :delete %>